// flow-typed signature: 37dbdd97aa22705a243d0c3d2e59df66
// flow-typed version: <<STUB>>/fixture-stdout_v0.2.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixture-stdout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixture-stdout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fixture-stdout/_example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fixture-stdout/_example.js' {
  declare module.exports: $Exports<'fixture-stdout/_example'>;
}
declare module 'fixture-stdout/index' {
  declare module.exports: $Exports<'fixture-stdout'>;
}
declare module 'fixture-stdout/index.js' {
  declare module.exports: $Exports<'fixture-stdout'>;
}
