// flow-typed signature: 7e895daaa84bdb8889d69a81b4a31b4c
// flow-typed version: <<STUB>>/netrc_v0.1.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netrc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netrc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netrc/test/netrc.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netrc/index' {
  declare module.exports: $Exports<'netrc'>;
}
declare module 'netrc/index.js' {
  declare module.exports: $Exports<'netrc'>;
}
declare module 'netrc/test/netrc.test.js' {
  declare module.exports: $Exports<'netrc/test/netrc.test'>;
}
