// flow-typed signature: dc26c1667947f89d6a102ba7a7fbecc4
// flow-typed version: <<STUB>>/shellwords_v0.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shellwords'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shellwords' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shellwords/lib/shellwords' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shellwords/lib/shellwords.js' {
  declare module.exports: $Exports<'shellwords/lib/shellwords'>;
}
